#print('Faustino Filho', 'Faustino Filho',42)
#print( 'A aranha pequenina \\(escalou a parede.')
#print()
#print('Caiu a chuva e levou a aranha.')
#print(' A aranha pequena' , 'subiu' , 'parede')
#print( 'Meu nome é', 'Pyton.')
#print('Monty Pyton.')
#print('Meu',' nome','é',sep='-',end='*')
#print('Monty','Python.',sep='*',end='\n')
#print('Progamação','Essenciais','em Python',sep='***',end='...')
#print('    ',end='\n',sep='*')
#print ('c')
#print('2')
#print(2)
#print('11111')
#print('11_111_11')
#print(0o123)
#print(0o123)
#print(0x123)
#print(0x300)
#print(2.5)
#print(10e8)
#print(3e8)
#print(0.0000000000000000000001)
#print(1e-22)
#print("Caixa D'água")
#print('Eu gosto\'Monty Pyton\'')
#print('Eu gosto "Monty Python"')
#print(True>False)
#print(True<False)
#print('"Eu sou"\n ""aprendizado"",\n """Python"""')
#print('"Eu sou"','""aprendizado""','"""Pynthon"""',sep='\n')
#print(0x1011)
#print(0b1011)
#print(2**3)
#print(2**3.)
#print(2.**3)
#print(2.**3.)
#print(2*3)
#print(2*3.)
#print(2.*3)
#print(2.*3.)
#print(6//3)
#print(6//3.)
#print(6.//3)
#print(6.//3.)
#print(6.//4)
#print(-6//4)
#print(6.//-4)
#print(-6/4)
#print(6./-4)
#print(14%4)
#print(14/4)
#print(30/1)
#print(-4+4)
#print(-4.+8)
#print(4+8)
#print(-4+-4)
#print(-4-4)
#print(-4.-8)
#print(-4-8)
#print(-4--4)
#print(2**2**3)
#print(25%13)
#print((2**4),(2*4.),(2*4))
#print((-2/4),(2/4),(2//4),(-2//4))
#print((2%-4),(2%4),(2**3**2))
#print(John,qtd_John,' maçãs','\n',
      #Maria,qtd_Maria,' maçãs','\n',
     # Adam,qtd_Adam,' maçãs',sep='')
#print('Total de maças: ', total_macas)

#minha_casa = 6 # da minha casa em km
#resultado= minha_casa * milhas
#print('Até minha casa são',resultado,'milhas')

##resultado = hrs * minha_casa 
#print('De minha_casa até o senac' ,resultado ,'segundos')
#

#idade=input("Qual sua idade ?")
#print("A idade fornecida foi",idade)

idade=int(input('Qual a sua idade?'))
#idade=int(idade)
print('A idade fornecida foi',idade)
print('Você nasceu em',2025-idade)
    
    





